name: Build and Deploy to SmarterASP

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Publish Application
        run: dotnet publish --configuration Release --no-build --output ./release

      - name: Deploy to SmarterASP
        shell: powershell
        run: |
          $msdeploy = "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"

          $siteName = 'pianomaker2-001-site2'
          $computer = 'https://win1232.site4now.net:8172/MsDeploy.axd?site=pianomaker2-001-site2'
          $user     = 'pianomaker2-001'
          $password = '${{ secrets.SERVER_PASSWORD }}'

          & $msdeploy `
            -verb:sync `
            -source:contentPath="$(pwd)\release" `
            -dest:contentPath="$siteName",ComputerName="$computer",UserName="$user",Password="$password",AuthType="Basic" `
            -allowUntrusted `
            -enableRule:AppOffline `
            -enableRule:DoNotDeleteRule
